language: go
go:
  - 1.8

install:
  - go get -u github.com/jteeuwen/go-bindata/...

addons:
  artifacts:
    paths:
      - out/clairctl-darwin-386
      - out/clairctl-darwin-amd64
      - out/clairctl-linux-386
      - out/clairctl-linux-amd64
    target_paths: latest
    working_dir: out
    
script:
- go generate ./clair
- go get github.com/mitchellh/gox
- gox -os="linux" -os="darwin" -arch="amd64 386" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-X github.com/jgsqware/clairctl/cmd.version=$(cat VERSION)"

deploy:
  provider: releases
  api_key:
    secure: HgOSNmBsqtA3CutTWnRNp2LNROeoPYyU+zO6ZzFH+tkG8Bif+KEtQx9fRv2YNB7+TSYUkaoT3v0XqkHhKe7GmhTD9mZ2v5isKHhD/FhP/qRDAxugzf66+mJJBhQ5tS9gz2hVK1E+tnHK1L3IVIh47zeXEd2VpciuxPaTwC2zAWi97EHFivjClD3uE2cc1HztDF95cq+eZzo5hfJn4mYuaMfnIGdPD3yKZY1+hQ7aby/+MxNyIbVwefgxV/fNPiVmM9u07+uzHWHKTikp8UyHvdKOyJp31S20i22velRC0xf6g4/d9rwfaw1zFMnjeA4ClRGwNief0cfKVtB7/KMwGC8UNiHvtDEIJn5yelSpqatde96eK7NJ58uTYsWRHM5RPW9MphpxhHPzBNXiz2m9sfZ7Frf3NeA94nZT1WAkoF4jjgWPNbPjOJzpz80dzzbNFUSWSrJFrJSaleLQwdPMi0fwTh2VG6gvhqYcLqW0GMVIUHFA905SuJwXje+IPh74RtjDmyMrwaONZQDqDfldXvY04kmoUsEkWPQkI3gQivp8Ep+IGpz+L8LPG5GR3whCu+OQqto1yIAFFdveFuD1VBgVvqJQwODkDkYux1UJNek1vbgtuGxuThWILZ16WcrxBl0l/FhFqxQ76tsH5A+57euVc5SFHDN6f7c5K2rzLcU=
  file: 
    - out/clairctl-darwin-386
    - out/clairctl-darwin-amd64
    - out/clairctl-linux-386
    - out/clairctl-linux-amd64
  skip_cleanup: true
  on:
    repo: jgsqware/clairctl
    tags: true
    branch: master
  
env:
  global:
    secure: QpHC0r/d3sUNZ4Tisu7IjRnE+exzUUdTRlWUvvepWA2/wdsvsh9IFKmPgHvmt/V46RtByc52HVwE/uE6gF8eVhRs4L4DP/gSi0TxmfNi2m+6EdL1MmFvdIVGfPZDDbFnNNXpWcNJGv5/UDJ8eke003Mtm7/qQfJqH3UzxoWnTrvsA7IHbhxomgsHOFqHU+e6fmaQ3q7neUJEci2HSPLehl11yBwMcsYyFjeW+33GVQeI0m2j1TrcldG3KN63tszIx7tHXTUrIK369nrndLjYWnc7Hi+k6Uc8vPh111/hLBG4UtxffP+/DTkhEtzxDNn3hn4zSKTMIyeKA/UhnySYchzDYOdVZoM0oVxAkbTcdTPWCxS75W1u3AW3QAGxScNEqmy5enrW+kGyRpd1zIRJ1qS2tHAVmos8N6bl5Rp9UJF5UITr9/DyQS93O9DOSY5Z6UVGI5J+MlG89Nr4XJ5NW4ak5yC5fc+9IwM58VMk8ULS3I0g/YBWsWRWHGZrHurnvcGbiXHk5S+anQsiYUV8n3OUa67ai7Duil3qiPklEhHeFZzmXrJMvLdeVxywfvIfKzSEGqDrUYw3hO9pkMzLxDQfvaNzAHWZGJ970N7apX2pnAUgPDsNb8cOnbDSjX36FICAiUZlrkpsz6O6h3Fm/2t/HDCyYH7gf6eJXypUOYc=
